API_VERSION: str = 'v1/'
EMAIL_FIELD_LENGTH: int = 254
TEXT_FIELD_LENGTH: int = 255
USERNAME_LENGTH: int = 150
MEASUREMENT_UNIT_LENTH: int = 10
MIN_COOKING_TIME: int = 1
MIN_INGREDIENT_AMOUNT: int = 1