volumes:
  pg_data:
  static:
  media:


services:
  db:
    image: postgres:13.10
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
  backend:
    image: eliaswide/foodgram_backend
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - static:/backend_static
      - media:/app/media
  frontend:
    image: eliaswide/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
  gateway:
    image: eliaswide/foodgram_gateway
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/backend_static
      - media:/app/media
    depends_on:
      - backend
    restart: always