# Generated by Django 3.2.3 on 2024-06-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'default_related_name': 'user', 'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'профили пользователей'},
        ),
    ]
